### ISSUE TITLE
NormSphericalCoords.dctl artifacts close to 10k nit

### ISSUE THREAD

**Issue by antonmeleshkevich** [JuanPabloZambrano/DCTL#2]
Hi Juan!
Could you please give me a hint, why is this happening?
This is exponential RGB chips displayed as Davinci Intermediate with applied 2 instances of NormSphericalCoords.dctl.  I get this artifacts starting slightly above 10k nit.
So the input to NormSphericalCoords.dctl can be considered as scene linear. After 2 instances of NormSphericalCoords.dctl for sandwiching I use CST to go from Linear to Davinci Intermediate.
Or this is the issue with the RGB chips itself, not NormSphericalCoords.dctl?
Thanks!

![Screenshot 2024-04-17 053748](https://github.com/JuanPabloZambrano/DCTL/assets/34407001/c5a021a3-7c25-4a70-bf5a-38c7c9ea57b2)

**Comment by JuanPabloZambrano** [comment]
I can't seem to be able to replicate, might be a Mac issue, I'll try to see it. by 10k nits what do you mean? 100 float? nits its only valid for nits based encoding so such as HLG or PQ.

**Comment by antonmeleshkevich** [comment]
Yes, I mean 100 in scene linear float. Also, I'm on Windows (Cuda).
And I was wrong, the artifacts appear above 100, not below. So you need to raise Number of Columns to 40 or so.

![Screenshot 2024-04-18 030621](https://github.com/JuanPabloZambrano/DCTL/assets/34407001/d7e5b953-48d4-40a8-9c12-1f16ef348b34)

**Comment by JuanPabloZambrano** [comment]
For some reason I am not getting the same issue, I used the same values for Thatcher's RGB chips, and I copied the latest NormSpherical dctl in my github just in case I had made some change only in my machine but I don't have it, I am in cuda, too . I am in Resolve 19 currently
