### ISSUE TITLE
Resolve 19 Beta 3

### ISSUE THREAD

**Issue by manofletters** [JuanPabloZambrano/DCTL#3]
Hello, wonder if DR 19 Beta 3 is compatible? Or am I using the wrong file?
Running Windows 10, 9900k and RTX3070.

![noshow](https://github.com/JuanPabloZambrano/DCTL/assets/64728841/8172af31-e31a-41fe-abc3-8126e1b9e7c4)

**Comment by JuanPabloZambrano** [comment]
It should, are you sure you downloaded the DCTL correctly? don't use the RAW button on GitHub as that will give you the wrong file
