### ISSUE TITLE
additional output colorspace for JP_2499_DRT

### ISSUE THREAD

**Issue by adamhawkey** [JuanPabloZambrano/DCTL#4]
Hi Juan, great job on the DCTL.

I needed to test on a device that is P3-D65 ST2084, so I made a modified version of your DCTL with this.

It would be great to have in the main build if you would not mind merging.

[JP_2499_DRT_addP3D65_PQ.dctl.zip](https://github.com/user-attachments/files/15744726/JP_2499_DRT_addP3D65_PQ.dctl.zip)

**Comment by JuanPabloZambrano** [comment]
Hey adam, I didn't see this one but somone made me this recommendation last week, so you should see it now. Its not the same as the one you did but it should be the same result
